### ISSUE TITLE
Suggestion: external project

### ISSUE THREAD

**Issue by GPMueller** [NOhs/git_info#3]
Some like to use utilities like this through CMake's `ExternalProject_Add` functionality (e.g. in order to download it during configuration instead of adding it to the source tree).

Does `ExternalProject_Add` work with this project?
If yes a demo of this in the Readme might be nice.

**Comment by NOhs** [comment]
I am not sure if this is possible as `ExternalProject_Add` is called during build. However, then the CMake file I provide would need to be called with an external cmake command I guess. And then I have no idea how you would add dependencies to your existing targets.
But I have no experience with `ExternalProject_Add` so maybe there are some clever ways to accomplish this.

**Comment by NOhs** [comment]
Will close this issue, as I do not see an easy way to do this atm. If you know of an easy way, just reopen, or even better feel free to make a pull request.
