### ISSUE TITLE
Suggestion: only warning instead of error if Python not found

### ISSUE THREAD

**Issue by GPMueller** [NOhs/git_info#4]
Maybe this would not be desirable but if Python is not found, the macros could produce empty strings or e.g. "unknown" instead of breaking the CMake build.

This would correspond to what might be desired behaviour if the folder is not part of a git repo (e.g. if a zip was downloaded), see #5.

**Comment by NOhs** [comment]
One of the things that I find most annoying about CMake is that it does not complain enough, making bug tracking a real pain (some command not working, then you find out that it was actually passed "" as an argument, then you find out that something about the code where you set your variable you passed must be wrong, etc. etc.).

If source code is shipped e.g. in a zip, then including a git info header in the first place is of course unnecessary I would guess (is it not?). If Python is not found, I could just copy the template files, but they are not correct C++/Python code, so errors would occur when they get included. Or I could not copy anything, but then the include would fail (except for when it is not included, but then again, why use this package).

So I am not sure if I should really change the current, very easy to understand behaviour.

**Comment by GPMueller** [comment]
A noticeable warning would definitely be necessary. But I agree that it is clearer to let the script break if Python is not found.

**Comment by NOhs** [comment]
I will close the issue for now. If at some point you find an error mode more suitable for this scenario than the one I used, feel free to reopen this issue.
